const COURSES_DATA = [
	{
		id: 1,
		category: 'marketing',
		categoryLabel: 'Marketing',
		title: 'The Ultimate Google Ads Training Course',
		price: 100,
		author: 'Jerome Bell',
		image: 'images/course-01.png',
	},
	{
		id: 2,
		category: 'management',
		categoryLabel: 'Management',
		title: 'Product Management Fundamentals',
		price: 480,
		author: 'Marvin McKinney',
		image: 'images/course-02.png',
	},
	{
		id: 3,
		category: 'hr',
		categoryLabel: 'HR & Recruiting',
		title: 'HR Management and Analytics',
		price: 200,
		author: 'Leslie Alexander Li',
		image: 'images/course-03.png',
	},
	{
		id: 4,
		category: 'marketing',
		categoryLabel: 'Marketing',
		title: 'Brand Management & PR Communications',
		price: 530,
		author: 'Kristin Watson',
		image: 'images/course-04.png',
	},
	{
		id: 5,
		category: 'design',
		categoryLabel: 'Design',
		title: 'Graphic Design Basic',
		price: 500,
		author: 'Guy Hawkins',
		image: 'images/course-05.png',
	},
	{
		id: 6,
		category: 'management',
		categoryLabel: 'Management',
		title: 'Business Development Management',
		price: 400,
		author: 'Dianne Russell',
		image: 'images/course-06.png',
	},
	{
		id: 7,
		category: 'development',
		categoryLabel: 'Development',
		title: 'Highload Software Architecture',
		price: 600,
		author: 'Brooklyn Simmons',
		image: 'images/course-07.png',
	},
	{
		id: 8,
		category: 'hr',
		categoryLabel: 'HR & Recruiting',
		title: 'Human Resources – Selection and Recruitment',
		price: 150,
		author: 'Kathryn Murphy',
		image: 'images/course-08.png',
	},
	{
		id: 9,
		category: 'design',
		categoryLabel: 'Design',
		title: 'User Experience. Human-centered Design',
		price: 240,
		author: 'Cody Fisher',
		image: 'images/course-09.png',
	},
	{
		id: 10,
		category: 'management',
		categoryLabel: 'Management',
		title: 'Social Media Marketing Strategy',
		price: 320,
		author: 'Eleanor Pena',
		image: 'images/course-01.png',
	},
	{
		id: 11,
		category: 'hr',
		categoryLabel: 'HR & Recruiting',
		title: 'Talent Acquisition Masterclass',
		price: 280,
		author: 'Robert Fox',
		image: 'images/course-02.png',
	},
	{
		id: 12,
		category: 'hr',
		categoryLabel: 'HR & Recruiting',
		title: 'Employee Engagement Programs',
		price: 190,
		author: 'Jenny Wilson',
		image: 'images/course-03.png',
	},
	{
		id: 13,
		category: 'hr',
		categoryLabel: 'HR & Recruiting',
		title: 'Compensation and Benefits Planning',
		price: 350,
		author: 'Wade Warren',
		image: 'images/course-04.png',
	},
	{
		id: 14,
		category: 'marketing',
		categoryLabel: 'Marketing',
		title: 'Content Marketing for Growth',
		price: 410,
		author: 'Annette Black',
		image: 'images/course-05.png',
	},
	{
		id: 15,
		category: 'development',
		categoryLabel: 'Development',
		title: 'UI Design Systems in Figma',
		price: 460,
		author: 'Devon Lane',
		image: 'images/course-06.png',
	},
	{
		id: 16,
		category: 'development',
		categoryLabel: 'Development',
		title: 'Frontend Performance Optimization',
		price: 550,
		author: 'Albert Flores',
		image: 'images/course-07.png',
	},
	{
		id: 17,
		category: 'marketing',
		categoryLabel: 'Marketing',
		title: 'Agile Project Leadership',
		price: 370,
		author: 'Courtney Henry',
		image: 'images/course-08.png',
	},
];

const CATEGORIES = [
	{ id: 'all', label: 'All' },
	{ id: 'marketing', label: 'Marketing' },
	{ id: 'management', label: 'Management' },
	{ id: 'hr', label: 'HR & Recruiting' },
	{ id: 'design', label: 'Design' },
	{ id: 'development', label: 'Development' },
];
